"use client";
import Image from "next/image";
import { useState } from "react";
import {practices} from "./practice-areas";
import {faqs} from "./faq";
import {CONTACT_EMAIL} from "./site-config";
const Arrow=()=> <span aria-hidden="true">↗</span>;
const quickQuestions=["Tuve un accidente de tránsito","La ART rechazó mi caso","Mi aseguradora no responde","Quiero consultar por un despido"];
function orientacion(q:string){const s=q.toLowerCase();if(s.includes("praxis")||s.includes("médic")||s.includes("medic")||s.includes("cirugía")||s.includes("cirugia"))return "Un resultado desfavorable no implica por sí solo mala praxis. Para evaluar el caso es importante conservar la historia clínica completa, consentimientos, estudios, fotografías, indicaciones y comprobantes. Deben analizarse la actuación profesional, el daño y su relación causal.";if(s.includes("quiebra")||s.includes("concurso")||s.includes("insolv"))return "En una crisis empresaria conviene reunir estados contables, detalle de acreedores, activos, juicios y obligaciones pendientes. La viabilidad de un concurso preventivo, acuerdo o proceso falencial depende de la situación patrimonial y societaria concreta.";if(s.includes("art")||s.includes("trabajo"))return "En un accidente laboral conviene conservar la denuncia, estudios, certificados y comunicaciones de la ART. Podemos revisar el rechazo, el alta médica o el porcentaje de incapacidad. Los plazos y la vía dependen de la jurisdicción y del estado del trámite.";if(s.includes("segur"))return "Guardá la póliza, denuncia del siniestro, respuesta de la compañía, presupuestos y comprobantes. Un rechazo o pago insuficiente debe analizarse según la cobertura contratada y las circunstancias del caso.";if(s.includes("despid"))return "No firmes acuerdos ni respondas intimaciones sin asesoramiento. Reuní recibos, telegramas, datos de registración y una cronología breve. La estrategia y los plazos dependen de cómo terminó la relación laboral.";if(s.includes("accidente")||s.includes("choque"))return "Primero asegurá la atención médica y conservá denuncia, fotos, datos de testigos, seguro y comprobantes. En rutas también importa registrar el estado de la calzada, el peaje y la presencia de animales u objetos.";return "Puedo brindarte una orientación inicial sobre accidentes, seguros, ART, trabajo, mala praxis médica, concursos y quiebras, ANSES, cobros, contratos, sucesiones y divorcios. Si el caso requiere revisar documentación o normativa específica, lo derivaré al Estudio."}
const faqJsonLd={"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqs.map(f=>({"@type":"Question",name:f.question,acceptedAnswer:{"@type":"Answer",text:f.answer}}))};
export default function Home(){
const[menuOpen,setMenuOpen]=useState(false);
const[chatOpen,setChatOpen]=useState(false);
const[query,setQuery]=useState("");
const[messages,setMessages]=useState<{from:"bot"|"user",text:string}[]>([{from:"bot",text:"Hola. Soy el asistente de orientación de Moulins Elgart Abogados. Contame brevemente qué ocurrió."}]);
const[openArea,setOpenArea]=useState<string|null>(null);
const[openFaq,setOpenFaq]=useState<number|null>(null);
const[formSent,setFormSent]=useState(false);
function ask(text=query){if(!text.trim())return;setMessages(m=>[...m,{from:"user",text},{from:"bot",text:orientacion(text)}]);setQuery("")}
function submitConsulta(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const data=new FormData(e.currentTarget);const nombre=String(data.get("nombre")||"");const email=String(data.get("email")||"");const tipo=String(data.get("tipo")||"Consulta general");const mensaje=String(data.get("mensaje")||"");const subject=`Consulta web${tipo?` - ${tipo}`:""}${nombre?` - ${nombre}`:""}`;const body=`Nombre: ${nombre}\nEmail de contacto: ${email}\nTipo de consulta: ${tipo}\n\nMensaje:\n${mensaje}`;window.location.href=`mailto:${CONTACT_EMAIL}?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;setFormSent(true)}
return <main>
<script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify(faqJsonLd)}}/>
<header className="topbar"><a className="brand" href="#inicio"><span className="brand-mark">ME</span><span>MOULINS ELGART<small>ABOGADOS</small></span></a><nav className={menuOpen?"nav open":"nav"} aria-label="Navegación principal"><a href="#estudio" onClick={()=>setMenuOpen(false)}>El estudio</a><a href="#areas" onClick={()=>setMenuOpen(false)}>Áreas de práctica</a><a href="#faq" onClick={()=>setMenuOpen(false)}>Preguntas frecuentes</a><a href="#cobertura" onClick={()=>setMenuOpen(false)}>Cobertura</a><a className="nav-cta" href="#consulta" onClick={()=>setMenuOpen(false)}>Consultar</a></nav><button className="menu" onClick={()=>setMenuOpen(!menuOpen)} aria-expanded={menuOpen} aria-label="Abrir menú"><span/><span/></button></header>
<section className="hero" id="inicio"><div className="hero-copy"><p className="eyebrow">Litigios · Accidentes · Seguros</p><h1>Defendemos<br/>tus derechos.</h1><p className="hero-lead">Experiencia, estrategia y trato directo para resolver conflictos complejos con una atención simple, ágil y 100% digital.</p><div className="hero-actions"><a className="button button-light" href="#consulta">Consultá tu caso <Arrow/></a><a className="text-link" href="#areas">Conocé nuestras áreas <span>↓</span></a></div><div className="hero-facts"><div><strong>100%</strong><span>Atención digital</span></div><div><strong>12</strong><span>Áreas de práctica</span></div></div></div><div className="hero-portrait"><Image src="./luis-moulins-elgart.png" alt="Dr. Luis Fernando Moulins Elgart" fill priority unoptimized sizes="(max-width:800px) 100vw,48vw"/><div className="portrait-label"><span>Abogado principal</span><strong>Dr. Luis F. Moulins Elgart</strong></div></div><span className="vertical-note">CABA · BUENOS AIRES · JUSTICIA FEDERAL · ENTRE RÍOS</span></section>
<section className="intro" id="estudio"><p className="section-number">01 / EL ESTUDIO</p><div><h2>Un equipo jurídico.<br/><em>Una estrategia para cada caso.</em></h2><p>Moulins Elgart Abogados interviene en negociaciones, operaciones complejas, reclamos y litigios. Combinamos análisis riguroso, seguimiento directo y tecnología para brindar soluciones claras a personas, empresas y organizaciones.</p><a className="dark-link" href="#perfil">Conocé al abogado principal <Arrow/></a></div></section>
<section className="practice-list" id="areas"><div className="section-heading"><p className="section-number">02 / ÁREAS DE PRÁCTICA</p><h2>Experiencia enfocada<br/>en resolver conflictos.</h2></div><p className="areas-intro">Elegí un área para ver cómo trabajamos y qué servicios ofrecemos.</p><div className="practice-rows">{practices.map(p=>{const open=openArea===p.slug;return <div className={open?"practice-row open":"practice-row"} key={p.slug}><h3><button className="practice-row-head" onClick={()=>setOpenArea(open?null:p.slug)} aria-expanded={open} aria-controls={`panel-${p.slug}`}><span className="num">{p.number}</span><span className="head-text"><span className="head-title">{p.title}</span><span className="lead">{p.lead}</span></span><span className="chev" aria-hidden="true"/></button></h3>{open&&<div className="practice-panel" id={`panel-${p.slug}`}>{p.description.map(d=><p key={d}>{d}</p>)}<h4>Servicios</h4><ul>{p.services.map(s=><li key={s}>{s}</li>)}</ul><a className="dark-link" href="#consulta">Consultar por esta área <Arrow/></a></div>}</div>})}</div></section>
<section className="digital"><div className="digital-copy"><p className="section-number">03 / ATENCIÓN DIGITAL</p><h2>Tu caso avanza.<br/><em>Vos no necesitás moverte.</em></h2><p>Coordinamos consultas, documentación, seguimiento y reuniones por medios digitales. Podés recibir atención desde cualquier lugar, con contacto directo con el profesional responsable.</p><div className="steps"><span><b>01</b>Contanos tu caso</span><span><b>02</b>Revisamos la documentación</span><span><b>03</b>Definimos la estrategia</span></div><a className="button button-copper" href="#consulta">Iniciar una consulta <Arrow/></a></div><div className="digital-map"><span>ATENCIÓN</span><strong>100%</strong><small>DIGITAL</small><div className="city c1">CABA</div><div className="city c2">LA PLATA</div><div className="city c3">CONCORDIA</div></div></section>
<section className="quality"><p className="section-number">04 / POLÍTICA DE CALIDAD</p><div><h2>Seriedad en el fondo.<br/><em>Calidad en cada detalle.</em></h2><p>Asumimos cada asunto con responsabilidad personal, método y una comunicación transparente. Nuestro compromiso es brindar asesoramiento de primera línea, con respuestas concretas y seguimiento permanente.</p><div className="quality-grid"><span><b>01</b>Análisis jurídico riguroso y estrategia documentada.</span><span><b>02</b>Información clara sobre avances, riesgos y alternativas.</span><span><b>03</b>Confidencialidad y cuidado responsable de la documentación.</span><span><b>04</b>Coordinación eficiente con especialistas y mejora continua.</span></div></div></section>
<section className="profile" id="perfil"><div className="profile-image"><Image src="./luis-moulins-elgart.png" alt="Luis Fernando Moulins Elgart" fill unoptimized sizes="45vw"/></div><div className="profile-copy"><p className="section-number">05 / ABOGADO PRINCIPAL</p><h2>Luis Fernando<br/>Moulins Elgart</h2><h4>Socio Director</h4><p>Abogado graduado en la Universidad Nacional de La Plata, con más de once años de experiencia profesional. Se especializó en Derecho Empresarial, Derecho Tributario y Derecho Administrativo y Administración Pública en la Universidad de Buenos Aires. Es también Escribano por la UNLP e Idóneo en Mercado de Capitales ante la CNV.</p><p>Su trayectoria integra litigios, derecho corporativo, contrataciones complejas, asuntos regulatorios, recupero de créditos y dirección de equipos jurídicos. Ha desarrollado su experiencia en ámbitos jurídicos de primera línea, el sector financiero, empresas y organismos públicos, manteniendo un enfoque personal sobre cada asunto.</p><ul><li>Abogado y Escribano — Universidad Nacional de La Plata</li><li>Posgrados en Derecho Empresarial, Tributario y Administrativo — UBA</li><li>Idóneo en Mercado de Capitales — CNV</li><li>CPACF · CALP · Matrícula Federal del Interior</li></ul></div></section>
<section className="coverage" id="cobertura"><p className="section-number">06 / ACTUACIÓN PROFESIONAL</p><h2>Cerca, estés<br/>donde estés.</h2><div className="coverage-grid"><div><span>01</span><strong>Ciudad Autónoma<br/>de Buenos Aires</strong></div><div><span>02</span><strong>Provincia de<br/>Buenos Aires</strong></div><div><span>03</span><strong>Justicia Federal<br/>en todo el país</strong></div><div><span>04</span><strong>Entre Ríos, con<br/>profesionales locales</strong></div></div><p className="coverage-note">La competencia y posibilidad de intervención se evalúan en cada caso concreto.</p></section>
<section className="faq" id="faq"><div className="section-heading"><p className="section-number">07 / PREGUNTAS FRECUENTES</p><h2>Antes de<br/>escribirnos.</h2></div><div className="faq-rows">{faqs.map((f,i)=>{const open=openFaq===i;return <div className={open?"faq-row open":"faq-row"} key={f.question}><h3><button className="faq-row-head" onClick={()=>setOpenFaq(open?null:i)} aria-expanded={open} aria-controls={`faq-panel-${i}`}><span className="head-title">{f.question}</span><span className="chev" aria-hidden="true"/></button></h3>{open&&<div className="faq-panel" id={`faq-panel-${i}`}><p>{f.answer}</p></div>}</div>})}</div></section>
<section className="contact" id="consulta"><div><p className="section-number">08 / CONSULTA INICIAL</p><h2>Conversemos sobre<br/>tu caso.</h2><p>Dejanos tus datos y una descripción breve. Al enviar, se abrirá tu programa de correo con la consulta prellenada dirigida a {CONTACT_EMAIL}.</p><button className="assistant-launch" onClick={()=>setChatOpen(true)}>Primero quiero orientación del asistente <Arrow/></button></div><form onSubmit={submitConsulta}><label>Nombre y apellido<input required name="nombre" placeholder="Tu nombre"/></label><label>Correo electrónico<input required name="email" type="email" placeholder="nombre@correo.com"/></label><label>Tipo de consulta<select required name="tipo" defaultValue=""><option value="" disabled>Seleccionar</option><option>Accidente de tránsito</option><option>Seguros</option><option>ART</option><option>Laboral</option><option>Mala praxis médica</option><option>Concurso o quiebra</option><option>Operación inmobiliaria</option><option>Previsional</option><option>Reajuste de aportes previsionales</option><option>Cobro o contrato</option><option>Sucesión o divorcio</option></select></label><label>Contanos brevemente<textarea required name="mensaje" rows={4} placeholder="¿Qué ocurrió?"/></label><button className="button button-copper" type="submit">Preparar consulta <Arrow/></button><small aria-live="polite">{formSent?`Se abrió tu programa de correo con la consulta dirigida a ${CONTACT_EMAIL}. Revisala y enviala desde ahí.`:`Se abrirá tu programa de correo con estos datos, dirigido a ${CONTACT_EMAIL}.`}</small></form></section>
<footer><a className="brand footer-brand" href="#inicio"><span className="brand-mark">ME</span><span>MOULINS ELGART<small>ABOGADOS</small></span></a><p>Litigios · Accidentes · Seguros<br/>Atención jurídica 100% digital.</p><div><a href="#areas">Áreas de práctica</a><a href="#faq">Preguntas frecuentes</a><a href="#perfil">Perfil</a><a href="#consulta">Contacto</a></div><small>© 2026 Moulins Elgart Abogados. La información de este sitio es general y no constituye asesoramiento legal.</small></footer>
<button className="chat-fab" onClick={()=>setChatOpen(!chatOpen)} aria-label="Abrir asistente"><span>✦</span>Consulta rápida</button>
{chatOpen&&<aside className="chat" aria-label="Asistente de orientación"><header><div><span>✦</span><strong>Asistente de orientación</strong><small>Respuesta inmediata</small></div><button onClick={()=>setChatOpen(false)} aria-label="Cerrar">×</button></header><div className="chat-disclaimer">Información general. No reemplaza el análisis de un abogado ni brinda conclusiones definitivas.</div><div className="messages" aria-live="polite">{messages.map((m,i)=><p key={i} className={m.from}>{m.text}{m.from==="bot"&&i>0&&<a href="#consulta" onClick={()=>setChatOpen(false)}> Derivar mi caso al Estudio →</a>}</p>)}</div>{messages.length===1&&<div className="quick">{quickQuestions.map(q=><button key={q} onClick={()=>ask(q)}>{q}</button>)}</div>}<div className="chat-input"><input value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")ask()}} placeholder="Escribí tu consulta..." aria-label="Consulta"/><button onClick={()=>ask()} aria-label="Enviar">↑</button></div></aside>}
</main>}
